# Generated by Django 3.2.6 on 2024-10-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_usuario_roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='acudiente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(default='Sin Dirección', max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numero_acudiente',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Acudiente',
        ),
    ]
